### ISSUE TITLE
getFormattedName not a function in 1.6

### ISSUE THREAD

**Issue by Casper-O** [trustpilot/plugin-prestashop#1]
bug in 2.50.718 orders.php line 286 affecting Prestashop 1.6

`
$imagePath = $link->getImageLink($product->link_rewrite, $image['id_image'], ImageType::getFormattedName('home'));
`
getFormattedName() is not a function in 1.6 - here it is called getFormatedName() but that function is deprecated since 1.7

how to fix: Make a check if PS is 1.7 or older to make this working.

since repo is not up to date, i can't do it

**Comment by vdabar** [comment]
Hey, sorry for the late response, The issue should be fixed in the latest version by adding a function that checks if the method exists. https://github.com/trustpilot/plugin-prestashop/blob/526702c2626454111de9a5b94df57d48b28e19ed/Trustpilot/orders.php#L278
