### ISSUE TITLE
Blocked a frame with origin...

### ISSUE THREAD

**Issue by adrianchuuk** [trustpilot/plugin-prestashop#3]
Hi guys,

Installed this module in PrestaShop 1.6.x.x and all fine until I try to log in to configure parameters, it automatically logs me out with the following error in console:

`Blocked a frame with origin "https://ecommscript-integrationapp.trustpilot.com" from accessing a frame with origin "https://www.domain.uk". Protocols, domains, and ports must match. `

There is no CSP in place on this domain.

**Comment by vilgro** [comment]
Hey @adrianchuuk 
Are you running on a domain that is registered on Trustpilot as well? 
Does your Prestashop back office going over HTTPS?

**Comment by adrianchuuk** [comment]
Hi @vilgro it's a claimed domain, yes. 

Yes on HTTPS.

**Comment by vilgro** [comment]
@adrianchuuk can you please drop an email to apps@trustpilot.com? (with your domain name and screenshot with error)

**Comment by adrianchuuk** [comment]
Sent just now including and screen capture video.

**Comment by arunas-stonis** [comment]
It usually happens because of X-Frame-Options or Content-Security-Policy headers are not allowing our plugin to load the site in iFrame. You can temporary disable these headers while setting up the plugin.

**Comment by adrianchuuk** [comment]
No such headers in nginx. Works fine in other browsers, like Firefox, doesn’t work on Safari. 

Regards,

Adrian
